# Form implementation generated from reading ui file 'C:\Users\yaros\Desktop\training-PM.02\pizzeria\ui\login.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox
import pymysql

class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(400, 300)
        LoginWindow.setMinimumSize(QtCore.QSize(360, 220))
        self.verticalLayout = QtWidgets.QVBoxLayout(LoginWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_username = QtWidgets.QLineEdit(parent=LoginWindow)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.verticalLayout.addWidget(self.lineEdit_username)
        self.lineEdit_password = QtWidgets.QLineEdit(parent=LoginWindow)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.verticalLayout.addWidget(self.lineEdit_password)
        self.btn_login = QtWidgets.QPushButton(parent=LoginWindow)
        self.btn_login.setMinimumSize(QtCore.QSize(0, 32))
        self.btn_login.setObjectName("btn_login")
        self.verticalLayout.addWidget(self.btn_login)
        self.btn_guest = QtWidgets.QPushButton(parent=LoginWindow)
        self.btn_guest.setMinimumSize(QtCore.QSize(0, 28))
        self.btn_guest.setObjectName("btn_guest")
        self.verticalLayout.addWidget(self.btn_guest)
        self.btn_guest.raise_()
        self.btn_login.raise_()
        self.lineEdit_password.raise_()
        self.lineEdit_username.raise_()

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Вход в систему"))
        self.lineEdit_username.setPlaceholderText(_translate("LoginWindow", "Логин"))
        self.lineEdit_password.setPlaceholderText(_translate("LoginWindow", "Пароль"))
        self.btn_login.setText(_translate("LoginWindow", "Войти"))
        self.btn_guest.setText(_translate("LoginWindow", "Вход как гость"))

    def check_user(self):
        login = self.lineEdit_username.text()
        password = self.lineEdit_password.text()

        connection = pymysql.connect(
            host="localhost",
            user="root",
            password="2281337",
            database="pizzeria",
            cursorclass=pymysql.cursors.DictCursor
        )

        cursor = connection.cursor()
        cursor.execute(
            "SELECT * FROM Users WHERE username = %s AND password_hash = %s",
            (login, password)
        )

        user = cursor.fetchone()
        connection.close()

        if user:
            role_id = user["role_id"]

            if role_id == 5:
                role = "Администратор"
            elif role_id == 4:
                role = "Менеджер"
            elif role_id == 3:
                role = "Оператор"
            elif role_id == 2:
                role = "Клиент"
            else:
                role = "Гость"

            QMessageBox.information(None, "Успех", f"Вход выполнен\nРоль: {role}")
        else:
            QMessageBox.warning(None, "Ошибка", "Неверный логин или пароль")

    def login_as_guest(self):
        QMessageBox.information(None, "Гость", "Вход выполнен как гость")

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)

    window = QtWidgets.QWidget()
    ui = Ui_LoginWindow()
    ui.setupUi(window)

    ui.btn_login.clicked.connect(ui.check_user)
    ui.btn_guest.clicked.connect(ui.login_as_guest)

    window.show()
    sys.exit(app.exec())