# Form implementation generated from reading ui file 'C:\Users\yaros\Desktop\training-PM.02\pizzeria\ui\client.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox
from pizzeria.db.database import get_connection


class Ui_ClientWindow(object):
    def setupUi(self, ClientWindow):
        ClientWindow.setObjectName("ClientWindow")
        ClientWindow.resize(600, 400)
        ClientWindow.setMinimumSize(QtCore.QSize(600, 400))
        self.verticalLayout = QtWidgets.QVBoxLayout(ClientWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=ClientWindow)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.table_menu = QtWidgets.QTableWidget(parent=ClientWindow)
        self.table_menu.setObjectName("table_menu")
        self.table_menu.setColumnCount(0)
        self.table_menu.setRowCount(0)
        self.verticalLayout.addWidget(self.table_menu)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=ClientWindow)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spin_quantity = QtWidgets.QSpinBox(parent=ClientWindow)
        self.spin_quantity.setMinimum(1)
        self.spin_quantity.setMaximum(20)
        self.spin_quantity.setObjectName("spin_quantity")
        self.horizontalLayout_2.addWidget(self.spin_quantity)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.btn_create = QtWidgets.QPushButton(parent=ClientWindow)
        self.btn_create.setObjectName("btn_create")
        self.verticalLayout.addWidget(self.btn_create)
        self.btn_logout = QtWidgets.QPushButton(parent=ClientWindow)
        self.btn_logout.setObjectName("btn_logout")
        self.verticalLayout.addWidget(self.btn_logout)

        self.retranslateUi(ClientWindow)
        QtCore.QMetaObject.connectSlotsByName(ClientWindow)

        self.parent = ClientWindow
        self.load_menu()
        self.btn_create.clicked.connect(self.create_order)
        self.btn_logout.clicked.connect(ClientWindow.close)

    def retranslateUi(self, ClientWindow):
        _translate = QtCore.QCoreApplication.translate
        ClientWindow.setWindowTitle(_translate("ClientWindow", "Окно клиента"))
        self.label.setText(_translate("ClientWindow", "Меню пиццерии"))
        self.label_2.setText(_translate("ClientWindow", "Количество"))
        self.btn_create.setText(_translate("ClientWindow", "Создать заказ"))
        self.btn_logout.setText(_translate("ClientWindow", "Выйти"))

    def load_menu(self):
        connection = get_connection()
        cursor = connection.cursor()

        cursor.execute("SELECT item_id, name, price FROM MenuItems")
        rows = cursor.fetchall()

        connection.close()

        self.table_menu.setColumnCount(3)
        self.table_menu.setHorizontalHeaderLabels(["ID", "Название", "Цена"])
        self.table_menu.setRowCount(len(rows))

        for i, row in enumerate(rows):
            self.table_menu.setItem(i, 0, QtWidgets.QTableWidgetItem(str(row["item_id"])))
            self.table_menu.setItem(i, 1, QtWidgets.QTableWidgetItem(str(row["name"])))
            self.table_menu.setItem(i, 2, QtWidgets.QTableWidgetItem(str(row["price"])))

    def create_order(self):
        row = self.table_menu.currentRow()

        item_id = self.table_menu.item(row, 0).text()
        price = float(self.table_menu.item(row, 2).text())
        quantity = self.spin_quantity.value()

        total = price * quantity

        connection = get_connection()
        cursor = connection.cursor()

        cursor.execute(
            "INSERT INTO Orders (user_id, total_amount) VALUES (%s,%s)",
            (self.user_id, total)
        )

        connection.commit()
        connection.close()

        QMessageBox.information(None, "Готово", "Заказ создан")